name = "image-background-remover"
compatibility_date = "2026-07-24"
pages_build_output_dir = "out"

[vars]
OAUTH_CLIENT_ID = "756474936491-bvq00uru5kv4kdul1ise1nkuns0tg9kt.apps.googleusercontent.com"
OAUTH_REDIRECT_URI = "https://shidaigpt.shop/api/auth/google/callback"
SESSION_COOKIE_NAME = "ibr_session"
PAYPAL_CLIENT_ID = "AYVI7mbMsvjyOIc_eLhHunUwVW6IYRgfTGHaDTUltyJFBEIuPwBeWNtPLHGcUFnVQts1LnVjQ7KwfrAG"
PAYPAL_ENV = "sandbox"
PAYPAL_CURRENCY = "USD"

[[d1_databases]]
binding = "DB"
database_name = "image-background-remover-auth"
database_id = "d78fafe7-e149-4e4a-a9d4-be89abf026a5"
