name = "image-background-remover"
compatibility_date = "2026-07-24"
pages_build_output_dir = "out"

# Fill database_id after creating the Cloudflare D1 database.
[[d1_databases]]
binding = "DB"
database_name = "image-background-remover-auth"
database_id = "d78fafe7-e149-4e4a-a9d4-be89abf026a5"
